### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by QianFuv**
1. Supplemented with English language files
2. Translated a small part with reference to the old language files

I have limited personal energy, so I'll continue to translate the rest when I have some free time.

### CODE REVIEW

**Comment by QianFuv** [comment]
Archive of old language files: https://gist.github.com/QianFuv/471820fe4c1ea0a3fa4c06e5dc25e6f6

**Review by thedarkcolour — CHANGES_REQUESTED** [review]
Please use two spaces for indentation instead of tabs

**Comment by thedarkcolour** [comment]
Also do you plan on updating this PR with more translations? Or would you like me to merge it immediately?

**Comment by QianFuv** [comment]
It's up to you, I'll probably refine the translation within a week, including any formatting errors, and if you'll be releasing a new version within a week, please merge this pr before releasing the new version.

**Comment by thedarkcolour** [comment]
I'll just fix the indentation myself and then merge, since I'm going to release an update very soon.

**Comment by thedarkcolour** [comment]
~~I fucked up the commit history :/~~
Nevermind, figured it out

**Review by thedarkcolour — APPROVED** [review]

**Pull request merged**
